In [17]:
# Tratamento da base de vendas
# Python + Pandas

In [18]:
# Importando o pandas
import pandas as pd

In [19]:
# Carregando a base
df = pd.read_csv('base_vendas.csv', encoding='utf-8-sig')

print('Base carregada!')
display(df.head())

Base carregada!

,Data_Venda,Produto,Categoria,Regiao,Quantidade,Preco_Unitario,Forma_Pagamento,Cliente,Faturamento
0,2025-01-01,Teclado,Acessórios,Sudeste,2.0,180,Cartão de Débito,CLI-0240,360.0
1,2025-01-01,Teclado,Acessórios,Nordeste,2.0,180,Cartão de Débito,CLI-0273,360.0
2,2025-01-01,Mouse,Acessórios,Sul,4.0,90,Cartão de Crédito,CLI-0025,360.0
3,2025-01-01,Cadeira,Móveis,Centro-Oeste,1.0,850,Cartão de Crédito,CLI-0036,850.0
4,2025-01-01,Mesa,Móveis,Centro-Oeste,1.0,650,Pix,CLI-0149,650.0

In [20]:
# Entendendo a base
print('\n--- DIMENSÕES DA BASE ---')
print('Linhas:', df.shape[0])
print('Colunas:', df.shape[1])

print('\n--- COLUNAS ---')

display(df.columns)

print('\n--- TIPOS DE DADOS ---')

display(df.dtypes)

--- DIMENSÕES DA BASE ---
Linhas: 650
Colunas: 9

--- COLUNAS ---

Index(['Data_Venda', 'Produto', 'Categoria', 'Regiao', 'Quantidade',
       'Preco_Unitario', 'Forma_Pagamento', 'Cliente', 'Faturamento'],
      dtype='str')

--- TIPOS DE DADOS ---

Data_Venda             str
Produto                str
Categoria              str
Regiao                 str
Quantidade         float64
Preco_Unitario       int64
Forma_Pagamento        str
Cliente                str
Faturamento        float64
dtype: object

In [21]:
# Verificando valores ausentes
print('\n ---VALORES AUSENTES ---')
display(df.isnull().sum())

 ---VALORES AUSENTES ---

Data_Venda          6
Produto             0
Categoria           0
Regiao              8
Quantidade         12
Preco_Unitario      0
Forma_Pagamento     7
Cliente             0
Faturamento        12
dtype: int64

In [22]:
# Corrigindo tipos de dados

# Data
df['Data_Venda'] = pd.to_datetime(
    df['Data_Venda'],
    errors='coerce'
)

# Números
df['Quantidade'] = pd.to_numeric(
    df['Quantidade'],
    errors='coerce'
)

df['Preco_Unitario'] = pd.to_numeric(
    df['Preco_Unitario'],
    errors='coerce'
)

df["Faturamento"] = pd.to_numeric(
    df["Faturamento"],
    errors='coerce'
)

In [23]:
# Padronizando textos
df['Produto'] = df['Produto'].str.strip()
df['Categoria'] = df['Categoria'].str.strip()
df['Regiao'] = df['Regiao'].str.strip()
df['Forma_Pagamento'] = (df['Forma_Pagamento'].str.strip())
df['Cliente'] = df['Cliente'].str.strip()

In [24]:
# Tratando valores ausentes

# Quantidade
# Usaremos a mediana para preencher os valores ausentes.

mediana_quantidade = df['Quantidade'].median()

df['Quantidade'] = df['Quantidade'].fillna(
    mediana_quantidade
)

# Região
df['Regiao'] = df['Regiao'].fillna(
    'Não informado'
)

# Forma de pagamento
df['Forma_Pagamento'] = (
    df['Forma_Pagamento'].fillna('Não informado')
)

In [25]:
# Tratando valores ausentes

print('\nDatas inválidas ou ausentes:')

print(
    df['Data_Venda'].isnull().sum()
)

# Como não é possível saber a data correta, vamos remover essas linhas.

df = df.dropna(
    subset=['Data_Venda']
)

Datas inválidas ou ausentes:
6

In [26]:
# Verificando valores duplicados

print('\nDuplicados encontrados:')

print(
    df.duplicated().sum()
)

# Removendo os duplicados

df = df.drop_duplicates()

Duplicados encontrados:
0

In [27]:
# Recalculando o faturamento

df['Faturamento'] = (
    df['Quantidade'] *
    df['Preco_Unitario']
)

In [28]:
# Criando colunas auxiliares

df['Ano'] = df['Data_Venda'].dt.year

df['Mes'] = df['Data_Venda'].dt.month

df['Mes_Ano'] = (
    df['Data_Venda'].dt.to_period('M').astype(str)
)

In [29]:
# Validar a base novamente

print('\n--- BASE DEPOIS DO TRATAMENTO ---')

display(df.head())


print('\n--- VALORES AUSENTES ---')

display(df.isnull().sum())


print('\n--- TIPOS DE DADOS ---')

display(df.dtypes)


print('\n--- DIMENSÕES FINAIS ---')

print('Linhas:', df.shape[0])
print('Colunas:', df.shape[1])

--- BASE DEPOIS DO TRATAMENTO ---

,Data_Venda,Produto,Categoria,Regiao,Quantidade,Preco_Unitario,Forma_Pagamento,Cliente,Faturamento,Ano,Mes,Mes_Ano
0,2025-01-01,Teclado,Acessórios,Sudeste,2.0,180,Cartão de Débito,CLI-0240,360.0,2025,1,2025-01
1,2025-01-01,Teclado,Acessórios,Nordeste,2.0,180,Cartão de Débito,CLI-0273,360.0,2025,1,2025-01
2,2025-01-01,Mouse,Acessórios,Sul,4.0,90,Cartão de Crédito,CLI-0025,360.0,2025,1,2025-01
3,2025-01-01,Cadeira,Móveis,Centro-Oeste,1.0,850,Cartão de Crédito,CLI-0036,850.0,2025,1,2025-01
4,2025-01-01,Mesa,Móveis,Centro-Oeste,1.0,650,Pix,CLI-0149,650.0,2025,1,2025-01

--- VALORES AUSENTES ---

Data_Venda         0
Produto            0
Categoria          0
Regiao             0
Quantidade         0
Preco_Unitario     0
Forma_Pagamento    0
Cliente            0
Faturamento        0
Ano                0
Mes                0
Mes_Ano            0
dtype: int64

--- TIPOS DE DADOS ---

Data_Venda         datetime64[us]
Produto                       str
Categoria                     str
Regiao                        str
Quantidade                float64
Preco_Unitario              int64
Forma_Pagamento               str
Cliente                       str
Faturamento               float64
Ano                         int32
Mes                         int32
Mes_Ano                       str
dtype: object

--- DIMENSÕES FINAIS ---
Linhas: 644
Colunas: 12

In [30]:
# Salvando a base limpa

df.to_csv(
    'vendas_limpa.csv',
    index=False,
    encoding='utf-8-sig'
)

print('\nBase limpa salva como:')
print('vendas_limpa.csv')

Base limpa salva como:
vendas_limpa.csv